### ISSUE TITLE
Error while getting new token

### ISSUE THREAD

**Issue by matriphe** [ept/uploadr.py#10]
Run: `python uploadr.py` and got this error
```
Getting new token
Error getting frob:(<class 'urllib2.URLError'>, URLError(error(54, 'Connection reset by peer'),), <traceback object at 0x103b07cf8>)
Traceback (most recent call last):
  File "uploadr.py", line 490, in <module>
    flick.upload()
  File "uploadr.py", line 310, in upload
    self.authenticate()
  File "uploadr.py", line 154, in authenticate
    self.getAuthKey()
  File "uploadr.py", line 191, in getAuthKey
    api.frob : FLICKR[ api.frob ],
KeyError: 'frob'
```

I'm running Python 2.7.10 on Mac OSX Yosemite

**Comment by Deepak-** [comment]
Also getting this error. Used to work fine, but now this error appears?
